=== mgalushka/rtorrentmanager/core/src/rtorrent/dialog/config.dtd
<!ELEMENT config (value|checkbox|select)+>
<!ELEMENT value (#PCDATA)>
<!ELEMENT checkbox (#PCDATA)>
<!ELEMENT select (option)+>
<!ELEMENT option (#PCDATA)>

<!ATTLIST config name CDATA #REQUIRED>
<!ATTLIST config title CDATA #REQUIRED>
<!ATTLIST value name CDATA #REQUIRED>
<!ATTLIST value text CDATA #REQUIRED>
<!ATTLIST value description CDATA "">
<!ATTLIST checkbox name CDATA #REQUIRED>
<!ATTLIST checkbox text CDATA #REQUIRED>
<!ATTLIST checkbox description CDATA "">
<!ATTLIST select name CDATA #REQUIRED>
<!ATTLIST select text CDATA #REQUIRED>
<!ATTLIST select description CDATA "">

=== mgalushka/rtorrentmanager/core/src/rtorrent/dialog/rtorrent.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE config SYSTEM "config.dtd">
<config title="Настройка rtorrent">
    <select name="service" text="Сервис" default="rtorrent" position="0">
        <option>rtorrent</option>
        <option>utorrent</option>
    </select>
    <value name="host" text="Хост" default="127.0.0.1" position="1"/>
    <value name="port" text="Scgi/Http порт" default="5000" position="2"/>
    <value name="login" text="Логин" default="admin" position="3" description="(Только для utorrent)"/>
    <value name="pass" text="Pass" default="" position="4" description="(Только для utorrent)"/>
    <value name="gui" text="Путь" default="gui" position="5" description="(Только для utorrent)"/>
</config>

=== mgalushka/rtorrentmanager/core/src/rtorrent/dialog/notice.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE config SYSTEM "config.dtd">
<config title="Настройка уведомлений">
    <value name="path" text="Шаблон ссылки" default="ftp://127.0.0.1/torrents/" position="1"/>
    <value name="replace" text="Строка для замены" default="/home/rtorrent/" position="2"/>
    <checkbox name="needEmailNotice" text="Получать уведомления по e-mail" default="false" position="3"/>
    <select name="levelEmailNotice" text="Level email уведомлений" default="update" position="4">
        <option>update</option>
        <option>finish</option>
    </select>
    <value name="host" text="Хост" default="smtp.mail.ru" position="5"/>
    <value name="login" text="Логин" default="" position="6"/>
    <value name="pass" text="Пароль" default="" position="7"/>
    <value name="fromMail" text="От" default="@mail.ru" position="8"/>
    <value name="toMail" text="Кому" default="@sms.beemail.ru" position="9"/>
    <checkbox name="needRssNotice" text="Генерировать rss ленту" default="true" position="10"/>
    <select name="levelRssNotice" text="Level rss уведомлений" default="finish" position="11">
        <option>update</option>
        <option>finish</option>
    </select>
</config>

=== mgalushka/rtorrentmanager/core/src/rtorrent/dialog/torrent.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE config SYSTEM "config.dtd">
<config title="Торрент">
    <checkbox name="watched" text="Наблюдаемый" default="false"/>
    <select name="tracker" text="Трекер" default="None">
        <option>None</option>
        <option>Rutracker</option>
        <option>LostFilm</option>
    </select>
    <value name="requestUrl" text="Url" default="" description="Подробнее об урл написано в настройках трекера"/>
    <value name="hash" text="Hash" default=""/>
</config>
